# Generated by Django 5.2.5 on 2025-09-27 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_rename_title_nft_name_rename_category_nft_price_irt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='positive_quantity',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='marketplace_cart_id_e8fe92_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='marketplace_nft_id_4cad35_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='marketplace_added_a_2c5b5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='marketplace_added_a_370eab_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='marketplace_updated_4f8da3_idx',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='created_at',
        ),
        migrations.AddField(
            model_name='nft',
            name='blockchain',
            field=models.CharField(choices=[('TON', 'TON Blockchain'), ('ETH', 'Ethereum'), ('POLY', 'Polygon'), ('BSC', 'Binance Smart Chain')], default='TON', max_length=20),
        ),
        migrations.AddField(
            model_name='nft',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='nft',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nfts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.ImageField(upload_to='nfts/'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_nfts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nft',
            name='price_irt',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='nft',
            name='price_polygon',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='nft',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
    ]
